export enum CustomFieldType {
  Text = 'text',
  TextArea = 'textarea',
  Tel = 'tel',
  Email = 'email',
  Password = 'password',
  Date = 'date',
  Time = 'time',
  Datetime = 'datetime',
  Number = 'number',
  Boolean = 'boolean',
  Select = 'select',
  MultiSelect = 'multiselect',
  File = 'file',
  Checkbox = 'checkbox',
  Radio = 'radio',
}
