# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Gembrs Development Deploy

on:
  workflow_dispatch:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, gembrs-server]
    strategy:
      matrix:
        node-version: [16]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - run: ls
    - run: rsync -a -u ~/actions-runner/gembrs-server_work/gembrs-server/gembrs-server/ /var/www/staging.gembrs.com/server
    - run: | 
        cd /var/www/staging.gembrs.com/server
        npm install
        npm run development